# Generated by Django 4.2.13 on 2025-08-07 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The main title for the generated content.",
                        max_length=255,
                    ),
                ),
                (
                    "input_params",
                    models.TextField(
                        help_text="A JSON object containig all user inputs for generation."
                    ),
                ),
                (
                    "generated_text",
                    models.TextField(
                        help_text="The full text content generation by the AI."
                    ),
                ),
                (
                    "generated_image_url",
                    models.URLField(
                        blank=True,
                        help_text="URL of the AI-generated image, if requested.",
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("POSTED_X", "Posted to X.com"),
                            ("POSTED_LINKEDIN", "Posted to LinkedIn"),
                            ("POSTED_ALL", "Posted to All Platforms"),
                        ],
                        default="DRAFT",
                        help_text="The current status of the content was genenrated.",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when the content was generated.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Content Histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
