from django.db import models
from django.conf import settings

# This model mirrors the `content_history` table in our D1 SQL schema.
# It is not used for database migrations but for data validation, serialization,
# and providing an object-oriented interface to our data within Django.

class ContentHistory(models.Model):
    """ 
    Stores a record of each piece of content generated by a user.
    """
    
    STATUS_CHOICE = [
        ('DRAFT', 'Draft'),
        ('POSTED_X', 'Posted to X.com'),
        ('POSTED_LINKEDIN', 'Posted to LinkedIn'),
        ('POSTED_ALL', 'Posted to All Platforms'),
    ]
    
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE, # If the user is deleted, their content is also deleted.
        related_name='content_history'
    )
    
    title = models.CharField(
        max_length=255,
        help_text="The main title for the generated content."
    )
    
    # JSONField is perfect for storing flexibal set of key value pairs
    # From the content generation form (niche, contextn tone, tags, etc)
    input_params = models.TextField(
        help_text="A JSON object containig all user inputs for generation."
    )
    generated_text = models.TextField(
        help_text="The full text content generation by the AI."
    )
    generated_image_url = models.URLField(
        max_length=1024,
        blank=True,
        null=True,
        help_text="URL of the AI-generated image, if requested."
    )
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICE,
        default='DRAFT',
        help_text="The current status of the content was genenrated."
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="The timestamp when the content was generated."
    )
    
    def __str__(self):
        """
        String representation of a content history item.
        """
        return f"'{self.title}' by {self.user.username} on {self.created_at.strftime('%Y-%m-%d')}"
    
    class Meta:
        ordering = ["-created_at"]
        verbose_name_plural = 'Content Histories'
    
    
    
    
