# Generated by Django 4.2.13 on 2025-08-07 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("x_com", "X.com"), ("linkedin", "LinkedIn")],
                        help_text="The social media platform.",
                        max_length=20,
                    ),
                ),
                (
                    "_access_token",
                    models.TextField(
                        db_column="access_token",
                        help_text="The encrypted OAuth access token.",
                    ),
                ),
                (
                    "_refresh_token",
                    models.TextField(
                        blank=True,
                        db_column="refresh_token",
                        help_text="The encrypted OAuth refresh token, if provided.",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The timestamp when the access token expires.",
                        null=True,
                    ),
                ),
                (
                    "profile_id",
                    models.CharField(
                        help_text="The user's unique ID or handle on the social platform.",
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Social Connections",
                "unique_together": {("user", "platform")},
            },
        ),
    ]
